package com.ct.framework.aut.commons;

public enum AppUiObjectNames {

    APP_UI_OBJECT,
    LOGIN_LINK_WELCOMESCREEN,
    SPLASHSCREEN_IMAGE_WELCOMESCREEN,
    TITLE_TEXT_WELCOMESCREEN,
    USERNAME_TEXT_LOGINSCREEN,
    PASSWORD_TEXT_LOGINSCREEN,
    LOGIN_BUTTON_LOGINSCREEN,
    FORGOTPWD_LINK_LOGINSCREEN,
    ERROR_MSG_LOGINSCREEN,

    SHARE_BTN_PINTEREST,

    TWITTER_LINK_ON_TIKTOK_PAGE




}
